# fly.toml app configuration file generated for quiet-field-9142 on 2023-05-23T02:46:15+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quiet-field-9142"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
